CREATE TABLE IF NOT EXISTS users
(
    USERNAME    VARCHAR(50) NOT NULL PRIMARY KEY,
    PASSWORD    VARCHAR(265) NOT NULL,
    ENABLED     BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS authorities
(
    USERNAME    VARCHAR(50) NOT NULL,
    AUTHORITY   VARCHAR(50) NOT NULL,
    FOREIGN KEY (USERNAME) REFERENCES users(USERNAME)
);

CREATE UNIQUE INDEX ix_auth_username ON authorities (USERNAME, AUTHORITY);
